### ISSUE TITLE
tidal-parse not building

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#940]
Does this make any sense to you @dktr0 ?

https://github.com/tidalcycles/Tidal/runs/7782195160?check_suite_focus=true#step:6:871

I'm getting the same error on my laptop as well (see below). I tried both with ghc 8.10.7 and 9.4.1, and the above is using 8.8.3 so I don't think it's ghc.. But I can't see anything that changed in tidal/tidal-parse/haskellish to trigger this either.

```
Building library for tidal-parse-0.0.1..
[1 of 2] Compiling Sound.Tidal.Parse.TH ( src/Sound/Tidal/Parse/TH.hs, dist/build/Sound/Tidal/Parse/TH.o, dist/build/Sound/Tidal/Parse/TH.dyn_o )
[2 of 2] Compiling Sound.Tidal.Parse ( src/Sound/Tidal/Parse.hs, dist/build/Sound/Tidal/Parse.o, dist/build/Sound/Tidal/Parse.dyn_o )

src/Sound/Tidal/Parse.hs:904:3: error:
    • Couldn't match type ‘a’ with ‘String’
      ‘a’ is a rigid type variable bound by
        the type signature for:
          pInt_pInt_p_p :: forall a.
                           H (Pattern Int -> Pattern Int -> Pattern a -> Pattern a)
        at src/Sound/Tidal/Parse.hs:902:1-73
      Expected type: H (Pattern Int
                        -> Pattern Int -> Pattern a -> Pattern a)
        Actual type: Haskellish
                       () (Pattern Int -> Pattern Int -> Pattern String -> Pattern String)
    • In the expression:
        (T.euclid <$ reserved "euclid")
          <|> (T.euclidInv <$ reserved "euclidInv")
          <|>
            (parser ::
               H (Int -> Pattern Int -> Pattern Int -> Pattern a -> Pattern a))
              <*!> parser
      In an equation for ‘pInt_pInt_p_p’:
          pInt_pInt_p_p
            = (T.euclid <$ reserved "euclid")
                <|> (T.euclidInv <$ reserved "euclidInv")
                <|>
                  (parser ::
                     H (Int -> Pattern Int -> Pattern Int -> Pattern a -> Pattern a))
                    <*!> parser
    • Relevant bindings include
        pInt_pInt_p_p :: H (Pattern Int
                            -> Pattern Int -> Pattern a -> Pattern a)
          (bound at src/Sound/Tidal/Parse.hs:903:1)
    |
904 |   $(fromTidal "euclid") <|>
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^...
Error: cabal: Failed to build tidal-parse-0.0.1. See the build log above for
details.
```

**Comment by dktr0** [comment]
Will take a look in a few hours!

**Comment by dktr0** [comment]
@yaxu I don't see the source for this problem, and can't reproduce it either. I made a PR that syncs tidal-parse and tidal (there were some fixes I made back in May that I forgot to send upstream...) but nothing in that jumps out as related to these issues. I can build with 8.8.4 just fine... https://github.com/tidalcycles/Tidal/pull/941

**Comment by dktr0** [comment]
One thought would be if, somehow, when building tidal-parse, it is accessing an old/cached version of Tidal wherein euclid euclidInv or fit' (the only tidal functions referenced here via TH that has not changed and is quite type agnostic) were defined in terms of String instead of a.

**Comment by dktr0** [comment]
After my PR it seems to work for 7 of the 8 CI runs, just not the stack one... but I still can't explain the error at all!? https://github.com/dktr0/Tidal/runs/7795063947?check_suite_focus=true

**Comment by ndr-brt** [comment]
> After my PR it seems to work for 7 of the 8 CI runs, just not the stack one... but I still can't explain the error at all!? https://github.com/dktr0/Tidal/runs/7795063947?check_suite_focus=true

the error is pretty hidden in the console log:
```
tidal-parse        > /home/runner/work/Tidal/Tidal/tidal-parse/src/Sound/Tidal/Parse.hs:24:53: error:
tidal-parse        >     Not in scope: ‘Haskellish.removeComments’
tidal-parse        >     Module ‘Language.Haskellish’ does not export ‘removeComments’.
tidal-parse        >    |
tidal-parse        > 24 |     x' = dropWhileEnd isSpace $ dropWhile isSpace $ Haskellish.removeComments x
tidal-parse        >    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dktr0** [comment]
@ndr-brt right! I actually meant that I couldn't explain the earlier error which @yaxu encountered. This one in the stack build is just because stack appears to be refusing to use the newer version of haskellish: ```WARNING: Ignoring tidal-parse's bounds on haskellish (>=0.3.2 && <0.4); using haskellish-0.2.4.3``` - it should be using 0.3.2 or 0.3.2.1...
